[Лукашевич Илья] Lab 1 variant 15
PashaKlybik/Prog-853504-2019 pull request #5
Opened 2019-02-22 10:39 UTC by JailSeed

2019-02-28 08:18 UTC, PashaKlybik requested changes

2019-02-28 08:18 UTC, PashaKlybik commented on lab1/lab1.c
> +			goto exit;
Удалить и больше никогда не использовать

2019-02-28 08:18 UTC, PashaKlybik commented on lab1/lab1.c
> +	for (i=2; i<100; i++) {
Переделать на цикл while

2019-02-28 08:18 UTC, PashaKlybik commented on lab1/lab1.c
> +	double ch[100],sum;
В этой задаче нет необходимости хранить старые данные и использовать массивы.

2019-03-01 20:01 UTC, JailSeed commented on lab1/lab1.c
> +	double ch[100],sum;
Переписал код, учитывая ваши замечания.

2019-03-01 20:01 UTC, JailSeed commented
Переписал код, учитывая ваши замечания.

2019-03-05 09:30 UTC, PashaKlybik requested changes

2019-03-05 09:30 UTC, PashaKlybik commented on lab1/lab1.c
> +        printf("Summa chisel: %d",sum,"\n");
Неверный формат вывода.

2019-03-05 09:30 UTC, PashaKlybik commented on lab1/lab1.c
> +#include <conio.h>
Эту библиотеку можно не использовать

2019-03-05 09:56 UTC, PashaKlybik reviewed
7

2019-03-05 09:56 UTC, PashaKlybik approved these changes

2019-03-05 09:57 UTC, merged